project_type: node
slug: Essentiaagency
port: 3000

domains:
  prod: essentiaagency.co.uk
  admin: admin.essentiaagency.co.uk

deploy_targets:
  main-hetz: hetzner
  dev: vercel
  preview: vercel

pgadmin_subdomain: dbui
pgadmin_subdomain: db
